// tools/gen_shoe_catalog.py 가 design/shoes-2026-09/catalog.json 으로 만든 파일 — 손으로 고치지 않는다.

/**
 * 새 신발 도감(2026-09-28). 번호 → 등급 · 시리즈 · 이름 · 그림 파일(web/assets/sneakers).
 * 서버 sneaker_models · 앱 ShoeCatalog 와 같은 표다. v3 도감에는 워커가 한 번 더한다(src/catalog.js).
 */
export const SHOE_MODELS = Object.freeze({
  1101: { rarity: 'RARE', series: 'RARE', en: 'Twin Arch Slide', ko: '트윈 아치 슬라이드', file: 'shoe_1101.webp' },
  1102: { rarity: 'RARE', series: 'RARE', en: 'Heel Loop Mule', ko: '힐 루프 뮬', file: 'shoe_1102.webp' },
  1103: { rarity: 'RARE', series: 'RARE', en: 'Toe Loop Sandal', ko: '토 루프 샌들', file: 'shoe_1103.webp' },
  1104: { rarity: 'RARE', series: 'RARE', en: 'Fisherman Cage Sandal', ko: '피셔맨 케이지 샌들', file: 'shoe_1104.webp' },
  1105: { rarity: 'RARE', series: 'RARE', en: 'Zero Drop Wide Slip-On', ko: '제로 드롭 와이드 슬립온', file: 'shoe_1105.webp' },
  1106: { rarity: 'RARE', series: 'RARE', en: 'Side Zip Commuter Runner', ko: '사이드 집 커뮤터 러너', file: 'shoe_1106.webp' },
  1107: { rarity: 'RARE', series: 'RARE', en: 'Split Heel Road Runner', ko: '스플릿 힐 로드 러너', file: 'shoe_1107.webp' },
  1108: { rarity: 'RARE', series: 'RARE', en: 'Lug Trail Runner', ko: '러그 트레일 러너', file: 'shoe_1108.webp' },
  1109: { rarity: 'RARE', series: 'RARE', en: 'Strap Road Runner', ko: '스트랩 로드 러너', file: 'shoe_1109.webp' },
  1110: { rarity: 'RARE', series: 'RARE', en: 'Amphibious Runner', ko: '앰피비어스 러너', file: 'shoe_1110.webp' },
  1111: { rarity: 'RARE', series: 'RARE', en: 'Wide Toe Road Runner', ko: '와이드 토 로드 러너', file: 'shoe_1111.webp' },
  1112: { rarity: 'RARE', series: 'RARE', en: 'Stability Road Runner', ko: '스태빌리티 로드 러너', file: 'shoe_1112.webp' },
  1113: { rarity: 'RARE', series: 'RARE', en: 'Strap Recovery Clog', ko: '스트랩 리커버리 클로그', file: 'shoe_1113.webp' },
  1114: { rarity: 'RARE', series: 'RARE', en: 'Retro Canvas Jogger', ko: '레트로 캔버스 조거', file: 'shoe_1114.webp' },
  1115: { rarity: 'RARE', series: 'RARE', en: 'Webbing Trail Runner', ko: '웨빙 트레일 러너', file: 'shoe_1115.webp' },
  1116: { rarity: 'RARE', series: 'RARE', en: 'Rocker Walk Jogger', ko: '로커 워크 조거', file: 'shoe_1116.webp' },
  1117: { rarity: 'RARE', series: 'RARE', en: 'Bungee Lace Runner', ko: '번지 레이스 러너', file: 'shoe_1117.webp' },
  1118: { rarity: 'RARE', series: 'RARE', en: 'Dial Road Runner', ko: '다이얼 로드 러너', file: 'shoe_1118.webp' },
  1119: { rarity: 'RARE', series: 'RARE', en: 'Tabi Split Toe Jogger', ko: '타비 스플릿 토 조거', file: 'shoe_1119.webp' },
  1120: { rarity: 'RARE', series: 'RARE', en: 'Packable Flex Runner', ko: '패커블 플렉스 러너', file: 'shoe_1120.webp' },
  1201: { rarity: 'EPIC', series: 'EPIC', en: 'Knit Wrap Runner', ko: '니트 랩 러너', file: 'shoe_1201.webp' },
  1202: { rarity: 'EPIC', series: 'EPIC', en: 'Stability Daily Trainer', ko: '스태빌리티 데일리 트레이너', file: 'shoe_1202.webp' },
  1203: { rarity: 'EPIC', series: 'EPIC', en: 'Tempo Rocker Trainer', ko: '템포 로커 트레이너', file: 'shoe_1203.webp' },
  1204: { rarity: 'EPIC', series: 'EPIC', en: 'Rock Guard Trail Runner', ko: '록 가드 트레일 러너', file: 'shoe_1204.webp' },
  1205: { rarity: 'EPIC', series: 'EPIC', en: 'Long Run Cushion Trainer', ko: '롱런 쿠션 트레이너', file: 'shoe_1205.webp' },
  1206: { rarity: 'EPIC', series: 'EPIC', en: 'Road-Trail Crossover Trainer', ko: '로드 트레일 크로스오버 트레이너', file: 'shoe_1206.webp' },
  1207: { rarity: 'EPIC', series: 'EPIC', en: 'Rock Plate Trail Trainer', ko: '록 플레이트 트레일 트레이너', file: 'shoe_1207.webp' },
  1208: { rarity: 'EPIC', series: 'EPIC', en: 'Track Interval Trainer', ko: '트랙 인터벌 트레이너', file: 'shoe_1208.webp' },
  1209: { rarity: 'EPIC', series: 'EPIC', en: 'Reflective Night Trainer', ko: '리플렉티브 나이트 트레이너', file: 'shoe_1209.webp' },
  1210: { rarity: 'EPIC', series: 'EPIC', en: 'Wet Road Trainer', ko: '웻 로드 트레이너', file: 'shoe_1210.webp' },
  1211: { rarity: 'EPIC', series: 'EPIC', en: 'Low Drop Form Trainer', ko: '로우 드롭 폼 트레이너', file: 'shoe_1211.webp' },
  1212: { rarity: 'EPIC', series: 'EPIC', en: 'Low Collar Gaiter Trail Runner', ko: '로우 칼라 게이터 트레일 러너', file: 'shoe_1212.webp' },
  1213: { rarity: 'EPIC', series: 'EPIC', en: 'Heel Cushion Pod Trainer', ko: '힐 쿠션 포드 트레이너', file: 'shoe_1213.webp' },
  1214: { rarity: 'EPIC', series: 'EPIC', en: 'External Heel Guide Trainer', ko: '익스터널 힐 가이드 트레이너', file: 'shoe_1214.webp' },
  1215: { rarity: 'EPIC', series: 'EPIC', en: 'Winter Microgrip Trainer', ko: '윈터 마이크로그립 트레이너', file: 'shoe_1215.webp' },
  1216: { rarity: 'EPIC', series: 'EPIC', en: 'Forefoot Hill Repeat Trainer', ko: '포어풋 힐 리피트 트레이너', file: 'shoe_1216.webp' },
  1217: { rarity: 'EPIC', series: 'EPIC', en: 'Arch Bridge Road Trainer', ko: '아치 브리지 로드 트레이너', file: 'shoe_1217.webp' },
  1218: { rarity: 'EPIC', series: 'EPIC', en: 'Polymer Plate Tempo Trainer', ko: '폴리머 플레이트 템포 트레이너', file: 'shoe_1218.webp' },
  1219: { rarity: 'EPIC', series: 'EPIC', en: 'Rocker Distance Trainer', ko: '로커 디스턴스 트레이너', file: 'shoe_1219.webp' },
  1220: { rarity: 'EPIC', series: 'EPIC', en: 'Wide Toe Flex Trainer', ko: '와이드 토 플렉스 트레이너', file: 'shoe_1220.webp' },
  1301: { rarity: 'LEGENDARY', series: 'LEGENDARY', en: 'Carbon Marathon Training Shoe', ko: '카본 마라톤 트레이닝 슈', file: 'shoe_1301.webp' },
  1302: { rarity: 'LEGENDARY', series: 'LEGENDARY', en: 'Stability Trainer', ko: '스태빌리티 트레이너', file: 'shoe_1302.webp' },
  1303: { rarity: 'LEGENDARY', series: 'LEGENDARY', en: 'Carbon Rockplate Trail Runner', ko: '카본 록플레이트 트레일 러너', file: 'shoe_1303.webp' },
  1304: { rarity: 'LEGENDARY', series: 'LEGENDARY', en: 'Light Midcut Trail Runner', ko: '라이트 미드컷 트레일 러너', file: 'shoe_1304.webp' },
  1305: { rarity: 'LEGENDARY', series: 'LEGENDARY', en: 'Ultradistance Wave Cushion Trainer', ko: '울트라디스턴스 웨이브 쿠션 트레이너', file: 'shoe_1305.webp' },
  1306: { rarity: 'LEGENDARY', series: 'LEGENDARY', en: 'Forefoot Marathon Interval Trainer', ko: '포어풋 마라톤 인터벌 트레이너', file: 'shoe_1306.webp' },
  1307: { rarity: 'LEGENDARY', series: 'LEGENDARY', en: 'Asymmetric TPU Hill Trainer', ko: '어시메트릭 TPU 힐 트레이너', file: 'shoe_1307.webp' },
  1308: { rarity: 'LEGENDARY', series: 'LEGENDARY', en: 'Desert Trail Runner', ko: '데저트 트레일 러너', file: 'shoe_1308.webp' },
  1309: { rarity: 'LEGENDARY', series: 'LEGENDARY', en: 'Heel Cage Stability Trainer', ko: '힐 케이지 스태빌리티 트레이너', file: 'shoe_1309.webp' },
  1310: { rarity: 'LEGENDARY', series: 'LEGENDARY', en: 'Full-Length Curve Interval Trainer', ko: '풀렝스 커브 인터벌 트레이너', file: 'shoe_1310.webp' },
  1311: { rarity: 'LEGENDARY', series: 'REDLINE', en: 'Redline 100m Sprint Spike', ko: '레드라인 100m 스프린트 스파이크', file: 'shoe_1311.webp' },
  1312: { rarity: 'LEGENDARY', series: 'REDLINE', en: 'Redline 800m Middle Distance Spike', ko: '레드라인 800m 미들 디스턴스 스파이크', file: 'shoe_1312.webp' },
  1313: { rarity: 'LEGENDARY', series: 'REDLINE', en: 'Redline 5000m Distance Spike', ko: '레드라인 5000m 디스턴스 스파이크', file: 'shoe_1313.webp' },
  1314: { rarity: 'LEGENDARY', series: 'REDLINE', en: 'Redline 5K·10K Racing Flat', ko: '레드라인 5K·10K 레이싱 플랫', file: 'shoe_1314.webp' },
  1315: { rarity: 'LEGENDARY', series: 'REDLINE', en: 'Redline Marathon Carbon Super Shoe', ko: '레드라인 마라톤 카본 슈퍼슈', file: 'shoe_1315.webp' },
  1316: { rarity: 'LEGENDARY', series: 'REDLINE', en: 'Redline Trail Race Shoe', ko: '레드라인 트레일 레이스 슈', file: 'shoe_1316.webp' },
  1317: { rarity: 'LEGENDARY', series: 'REDLINE', en: 'Redline Triathlon Transition Racer', ko: '레드라인 트라이애슬론 트랜지션 레이서', file: 'shoe_1317.webp' },
  1318: { rarity: 'LEGENDARY', series: 'REDLINE', en: 'Redline Steeplechase Drain Spike', ko: '레드라인 스티플체이스 드레인 스파이크', file: 'shoe_1318.webp' },
  1319: { rarity: 'LEGENDARY', series: 'REDLINE', en: 'Redline Half Marathon Road Racer', ko: '레드라인 하프 마라톤 로드 레이서', file: 'shoe_1319.webp' },
  1320: { rarity: 'LEGENDARY', series: 'REDLINE', en: 'Redline Cross Country Spike', ko: '레드라인 크로스컨트리 스파이크', file: 'shoe_1320.webp' },
  1321: { rarity: 'LEGENDARY', series: 'FINISH', en: 'Finish Championship Marathon Super Shoe', ko: '피니시 챔피언십 마라톤 슈퍼슈', file: 'shoe_1321.webp' },
  1322: { rarity: 'LEGENDARY', series: 'FINISH', en: 'Finish Elite 100m Sprint Spike', ko: '피니시 엘리트 100m 스프린트 스파이크', file: 'shoe_1322.webp' },
  1323: { rarity: 'LEGENDARY', series: 'FINISH', en: 'Finish Elite Middle Distance Spike', ko: '피니시 엘리트 미들 디스턴스 스파이크', file: 'shoe_1323.webp' },
  1324: { rarity: 'LEGENDARY', series: 'FINISH', en: 'Finish Ultratrail Championship Racer', ko: '피니시 울트라트레일 챔피언십 레이서', file: 'shoe_1324.webp' },
  1325: { rarity: 'LEGENDARY', series: 'FINISH', en: 'Finish Championship 5K·10K Road Flat', ko: '피니시 챔피언십 5K·10K 로드 플랫', file: 'shoe_1325.webp' },
  1326: { rarity: 'LEGENDARY', series: 'FINISH', en: 'Finish Championship Cross Country Spike', ko: '피니시 챔피언십 크로스컨트리 스파이크', file: 'shoe_1326.webp' },
  1327: { rarity: 'LEGENDARY', series: 'FINISH', en: 'Finish Championship Steeplechase Spike', ko: '피니시 챔피언십 스티플체이스 스파이크', file: 'shoe_1327.webp' },
  1328: { rarity: 'LEGENDARY', series: 'FINISH', en: 'Finish Championship 400m Sprint Spike', ko: '피니시 챔피언십 400m 스프린트 스파이크', file: 'shoe_1328.webp' },
  1329: { rarity: 'LEGENDARY', series: 'FINISH', en: 'Finish Championship 800m Middle Distance Spike', ko: '피니시 챔피언십 800m 미들 디스턴스 스파이크', file: 'shoe_1329.webp' },
  1330: { rarity: 'LEGENDARY', series: 'FINISH', en: 'Finish Championship Half Marathon Carbon Racer', ko: '피니시 챔피언십 하프 마라톤 카본 레이서', file: 'shoe_1330.webp' },
})
